# Generated by Django 6.0.2 on 2026-02-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0003_complain_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
