# Generated by Django 6.0.2 on 2026-02-25 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0006_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='complain',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Dislike', 'Dislike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='complain',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complains.complain'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
