# Generated by Django 6.0.2 on 2026-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0007_alter_like_unique_together_complain_liked_like_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=10),
        ),
    ]
